name: mlops_exercise
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pytest=6.2.2
  - pip=20.3.3
  - git=2.30.2
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - requests=2.24.0
  - hydra-core=1.0.6
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - plotly==4.4.1
  - pillow=8.1.2
  - ipython=7.21.0
  - notebook=6.2.0
  - pylint
  - autopep8
  - pytest
  - dataclasses
  - pip:
      - wandb==0.10.21
      - mlflow==1.23.0
      - hydra-joblib-launcher==1.1.2